### PR TITLE
Add image to SEO configuration

### LINKED ISSUE #6: Add image
If we add an image to the SEOTranslation, we could use this for both `og:image` and `twitter:image`. If there's no image set, we can fallback on the first product image.

### PR DESCRIPTION
**Pull request by KaiCMueller**
closes #6

Requested was an "image" field in the SEOTranslation Entity. 

The field was added. Form, Views, Translations were added.
If the image url is set at the product seo configuration it will be used, otherwise a fallback image from the product is used.
I removed a dump I found in "_seo.html.twig".

Please let me know what you think 😃

### CODE REVIEW

**Comment by JoppeDC** [comment]
Thank you @KaiCMueller ! I think it would be a lot easier if we could use the `ImageType` as used in other entities, instead of using an external url. Do you think you'd be able to make this change?

Also, there have been some changes on the master branch, so make sure you're up to date 😉

**Comment by KaiCMueller** [comment]
@JoppeDC Sure, I will care about that. ImageType is new to me, I never worked with Sylius.

**Comment by JoppeDC** [comment]
Great! If you need any help, let me know 😉

**Comment by KaiCMueller** [comment]
@JoppeDC please specify the way you want the images to be added: should there be a complete separate image handling for the seo entity (which means you can add a new image but if you want to use a product image you would have a duplicate image) or should the product images be used?

Sorry I'm not familiar how images are handled in Sylius, maybe you can give me a hint where I can find a good example.

**Comment by JoppeDC** [comment]
@KaiCMueller The idea is to add an image field for the og:image, and the twitter:image. We can use one field for both these meta tags. If no image is set here, we can fallback to the product image in the template itself.
[You can find some info on adding images here.](https://docs.sylius.com/en/1.6/cookbook/images/images-on-entity.html) This is an example to add multiple images, but we only need one so no Collection needed.

**Comment by KaiCMueller** [comment]
@JoppeDC 

From the documentation I should register the event listener like this:
event: sylius.shipping_method.pre_create

I don't know how to change this to work with the ProductSeoTranslation entity. I got everything working so far, but the uploadImages is not triggered on pre_create and pre_update since I do not know the name of the event for that entity. Maybe you have an idea?
 
What I have so far in services.yaml:

```
    app.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        parent: sylius.listener.images_upload
        autowire: true
        autoconfigure: false
        public: false
        #tags:
        #    - { name: kernel.event_listener, event: app.product_seo_translation.pre_create, method: uploadImages }
        #    - { name: kernel.event_listener, event: app.product_seo_translation.pre_update, method: uploadImages }
        tags:
            -
                name: doctrine.orm.entity_listener
                event: preUpdate
                entity: JoppeDc\SyliusBetterSeoPlugin\Entity\ProductSeoTranslation
                method: uploadImages
            -
                name: doctrine.orm.entity_listener
                event: preCreate
                entity: JoppeDc\SyliusBetterSeoPlugin\Entity\ProductSeoTranslation
                method: uploadImages
```

**Comment by JoppeDC** [comment]
@KaiCMueller I'm not 100% sure, but you can check in the profiler, under Events -> Not Called Listeners, maybe you can spot it in there. You could also try it on the Product pre create, since its essentially part of that entity.

**Comment by KaiCMueller** [comment]
@JoppeDC I spent so many hours on this now but I can't get the image upload to work. Feels like I'm 90% there. Problem: When I'm adding an Image the $image property of the SeoTranslationEntity is always null. It seems like the form field and the upload file are not connected properly. I see the file is uploaded but the ProductSeoTranslationImageUploadListener is always getting "null" value for the image. It would be great if you can have a look into it, I'm pretty sure it is something totally obvious but I'm just into that task for too long.

**Comment by JoppeDC** [comment]
@KaiCMueller I'll have a look when i get some spare time on my hands. If you're that close i'm sure we could figure this out 😉

**Comment by JoppeDC** [comment]
@KaiCMueller I've been fiddling around with it a little bit, but unfortunatly i haven't been able to get it to work either. Thanks for your contributions, and i'm leaving this open in case we do figure it out or someone else might have some tips.

**Comment by KaiCMueller** [comment]
@JoppeDC I see. It used to work fine when I implemented it with multi-image upload. But since having multiple images here makes no sense I switched to the single image upload.

**Comment by JoppeDC** [comment]
Hmm, how about implementing the multi image upload, and limiting it to one? Maybe the Sylius builtin image system isn’t designed for single uploads. The single upload also doesnt have the preview etc. That multi upload has

**Comment by KaiCMueller** [comment]
Yep that sounds reasonable. I will get back to it in the next days.

**Comment by KaiCMueller** [comment]
@JoppeDC The image upload is working now. But it doesn't have the fancy image preview. I implemented validation as documented here: https://docs.sylius.com/en/1.6/customization/validation.html#how-to-customize-validation
Unfortunately it doesn't have any effect on the form validation for whatever reason.

So what is missing:
- Convenient image upload form with image preview
- Validation for image upload (limit to one image, define image size, etc.)

**Comment by JoppeDC** [comment]
Hi @KaiCMueller . I have a small update on this. I've been able to get the single image upload to work, preview and everything.
All thats left to do now is some refactoring and cleanup, and then i'll push this as tag 1.0.0, the first release!

For this reason, i'll close this PR. Thanks for the help, it was really usefull!

**Pull request closed without merging**
