### PR TITLE
Fix "The table with name 'sylius_product' already exists."

### PR DESCRIPTION
**Pull request by antiseptikk**
See #19

### CODE REVIEW

**Comment by JoppeDC** [comment]
Thanks for the PR @antiseptikk. I've been testing it but there still appears to be an issue when you try to save products. 
I'm going to have to figure this out first before i can merge this.

For some reason the translations for the Seo entity are not initialized, giving an error on save. 

`php.CRITICAL: Uncaught Error: Return value of JoppeDc\SyliusBetterSeoPlugin\Entity\Seo::getTranslations() must implement interface Doctrine\Common\Collections\Collection`

**Comment by antiseptikk** [comment]
Hi @JoppeDC, I fixed the pull request and updated the readme.

**Comment by JoppeDC** [comment]
@antiseptikk Thanks a lot! Appears to be completely functional again.

**Comment by bybilvanis** [comment]
Thanks @antiseptikk

**Comment by JoppeDC** [comment]
Merged & tagged @ 1.0.1

**Pull request merged**
