### PR TITLE
Spanish Translation

### LINKED ISSUE #3: I'll add Spanish translation
Let me know (ping me here in GitHub) if you add/remove/modify translation keys in the future, so I can update it.

### PR DESCRIPTION
**Pull request by migmolrod**
Fixes #3 

Added Spanish translation file (`messages.es.yml`)

Let me know (ping me here in GitHub for example) if you add/remove/modify any translation key so I can update the translation file.

### CODE REVIEW

**Comment by JoppeDC** [comment]
Thanks @migmolrod! If you could adjust your spanish version, we can merge this! 🥳

**Comment by migmolrod** [comment]
Oh, I see. There must be something with GitHub caching forks or something. Because I made a mistake in my fork, then deleted and recreated it and the changes were there. Except they weren't there XD Strange.

**Comment by migmolrod** [comment]
Done.

I think.

**Comment by JoppeDC** [comment]
Looking great, thanks @migmolrod!

**Pull request merged**
