### PR TITLE
doc: Local development

### PR DESCRIPTION
**Pull request by tarlepp**
This PR moves project local development documentation to separated directory and adds link to that to main README.md

### CODE REVIEW

**Review by JoppeDC — APPROVED** [review]

**Comment by tarlepp** [comment]
Fixed conflicts

**Comment by tarlepp** [comment]
Hmm, for some reason Scrutinizer hasn't reported back it status correctly - https://scrutinizer-ci.com/g/JoppeDC/SyliusBetterSeoPlugin/inspections/813c5000-a075-4263-bf2d-b1052ca9e2cd

**Comment by JoppeDC** [comment]
I noticed, thats the reason its not merged yet (Can’t merge on mobile without Scrutinizer giving a green light)

**Comment by tarlepp** [comment]
got that fixed by triggering scrutinizer again :D

**Comment by JoppeDC** [comment]
Yup, decided to give it a try and rerun. Thanks again!

**Pull request merged**
